### ISSUE TITLE
Inconsistencies between knora-py library and knora's doc regarding `knora-base:listNodeName` property

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/dsp-tools#20]
The `knora-xml-import` library uses a list property which is not mandatory: `knora-base:listNodeName`.

See `Listnode` class definition: 

```
knora-base:ListNode rdf:type owl:Class ;

          rdfs:subClassOf [ rdf:type owl:Restriction ;
                            owl:onProperty knora-base:listNodeName ;
                            owl:maxCardinality "1"^^xsd:nonNegativeInteger
                          ] ,
```
But maybe this property should be made mandatory in list definition in general because if the data are uploaded without it in Knora API without using the `knora-create-ontology` library (which `knora-xml-import` allows), then `knora-xml-import` won't be able fulfil the data import.

**Comment by mrivoal** [comment]
I think there is an inconsistency in the use of the property `listNodeName` between the library (`knora-create-ontology` and `knora-xml-import`) and lists definition in `knora-base` ontology and in knora's doc.

Using the providing example (test-onto.json) `knora-create-ontology` will generate a list whose rootnode will be assigned the property `listNodeName`.

But in knora’s doc, only  listnodes that are not rootnodes should have a `listNodeName` property.

What is also problematic is the fact that, if you try to import with `knora-xml-import` a resource with `listValue` related to a list already uploaded to the triplestore (a .ttl which is correct from knora's view but whose rootnode doesn't have a `listNodeName`), then an error is thrown :

```
Traceback (most recent call last):
  File "/usr/local/bin/knora-xml-import", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/knora/xml2knora.py", line 616, in main
    program(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/knora/xml2knora.py", line 583, in program
    schema = con.create_schema(shortcode, ontology)
  File "/usr/local/lib/python3.7/site-packages/knora/knora.py", line 1692, in create_schema
    "nodes": self.list_creator(clist["children"])
KeyError: 'name'
``` 
because `knora-xml-import` is looking for the `listNodeName` property of every rootnode. If you add one in the list.ttl, then the import of the resource with `knora-xml-import` will run correctly (but then you go against knora's doc).

I think this inconsistencies should be fixed because they bring confusion as for what are the correct properties for a rootnode.
